# Site settings
title: Bill Martin
email: bill@billmartin.io
url: http://billmartin.io
description: "Full-Stack Web Developer, Musician, and Great Outdoors Enthusiast."
meta_author: Bill Martin

about:
  header: About
  content:
      left: By day, I code payment, enrollment, and quoting web applications for some of the industry's top health insurance companies, whilst striving for <a href="http://blog.codinghorror.com/a-pragmatic-quick-reference/" target="_new">Pragmatic Programmer</a> perfection.
      right: By night, I play guitar in three bands, camp, kayak, hike, play video games, read fantasy, sci-fi, & programming books, and ponder Life, The Universe, and Everything.
      bottom: I live in Manchester, NH.
  interests:
    header: Interests as of Late
    content:
      left:
        header: Now
        list:
          - item: SOLID Principles
          - item: Design Patterns
          - item: PhpStorm Mastery
      center:
        header: Soon
        list:
          - item: Sublime Mastery
          - item: ES2015
          - item: React
      right:
        header: Later
        list:
          - item: JS Best Practices
          - item: HTML5/CSS3/SASS
          - item: Laravel
  button:
    text: Download My Resume
    href: /resume/bill-martin-resume.pdf

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname: https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: billmartin

# If you have Google Analytics account setup, enter your tracker ID, eg. A-12312312-1
google_analytics_tracker_id: A-89823208-1

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 101010 #80B3FF
  primary-rgb: "255,0,0" #"128,179,255"
  secondary-light: 7a7c71 #FD6E8A
  secondary: 5a5c51 #FD6E8A
  secondary-dark: 363730 #A2122F
  blog-text: 222
  link: 1a77bd

# Blog settings
blog:
  labels:
    modal-close: Close

# Markdown/syntax highlighter settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Portfolio settings
portfolio:
  labels:
    client: Client
    project-date: Date
    application: Application
    languages: Languages
    concepts: Concepts
    tools: Tools
    stack: Stack
    modal-close: Close

# Footer settings
footer:
  location-header: Location
  location: Manchester, NH
  copyright: Bill Martin. All Rights Reserved.
  social: My Other Whereabouts
  new-thoughts: New Thoughts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc. search them in main.css)
social:
  - title: github
    tooltip: "Github: Code I am writing"
    url: https://github.com/bill-c-martin
  - title: linkedin
    tooltip: "Linkedin: Places I've worked"
    url: https://www.linkedin.com/in/billmartin9
  - title: codeschool
    tooltip: "Codeschool: Skills I am learning"
    url: https://www.codeschool.com/users/90602
  - title: laracasts
    tooltip: "Laracasts: Skills I am learning"
    url: https://laracasts.com/@wcmarti2
  - title: stack-overflow
    tooltip: "Stack Overflow: Solutions I've been exchanging"
    url: http://stackoverflow.com/users/5743565/bill-martin
  - title: goodreads
    tooltip: "Goodreads: Books I've been reading"
    url: http://www.goodreads.com/billmartin
  - title: rss
    tooltip: Subscribe to RSS feed
    url: /feed.xml

# Credits content
credits: '<a href="https://github.com/bill-c-martin/bill-c-martin.github.io">Fork my portfolio on github</a>'

# Build settings
permalink: pretty